apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .Values.namespace }}-limit
  namespace: {{ .Values.namespace }}
spec:
  limits:
    - type: PersistentVolumeClaim
      max:
        storage: {{ .Values.limits.max.storage }}       
      defaultRequest:
        storage: {{ .Values.limits.defaultRequest.storage }}
