apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: sqliteClaim
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
    storageClassName: standard