apiVersion: v1
kind: PersistentVolume
metadata:
    name: {{ .Values.namespace }}-sqlite-pv
spec:
    capacity:
        storage: 1Gi
    volumeMode: Filesystem
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    storageClassName: standard
    hostPath:
        path: {{ .Values.datapath }}