apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ .Values.namespace }}-sqlite-claim
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
    storageClassName: standard