namespace: prod
requests:
  cpu: "3"
  memory: "3Gi"
limits:
  cpu: "3"
  memory: "3Gi"
  max:
    storage: "3Gi"
  defaultRequest:
    storage: "3Gi"
datapath: "/app/data/prod"
volumes: 
- name: my-sqlite
  persistentVolumeClaim:
    claimName: prod-sqlite-claim